-- MySQL Script generated by MySQL Workbench
-- Fri Apr  3 00:00:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema moviereservation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moviereservation` ;

-- -----------------------------------------------------
-- Schema moviereservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviereservation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `moviereservation` ;

-- -----------------------------------------------------
-- Table `moviereservation`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservation`.`movies` ;

CREATE TABLE IF NOT EXISTS `moviereservation`.`movies` (
  `movie_id` INT(11) NOT NULL,
  `movie_name` VARCHAR(40) NULL DEFAULT NULL,
  `movie_genre` VARCHAR(20) NULL DEFAULT NULL,
  `movie_rating` VARCHAR(20) NULL DEFAULT NULL,
  `movie_director` VARCHAR(20) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviereservation`.`cinemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservation`.`cinemas` ;

CREATE TABLE IF NOT EXISTS `moviereservation`.`cinemas` (
  `cinema_id` INT(11) NOT NULL,
  `movie_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cinema_id`),
  INDEX `movieC_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `movieC_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviereservation`.`movies` (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviereservation`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservation`.`customers` ;

CREATE TABLE IF NOT EXISTS `moviereservation`.`customers` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviereservation`.`timeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservation`.`timeslots` ;

CREATE TABLE IF NOT EXISTS `moviereservation`.`timeslots` (
  `timeslot_id` INT(11) NOT NULL,
  `time_start` VARCHAR(20) NULL DEFAULT NULL,
  `movie_id` INT(11) NULL DEFAULT NULL,
  `cinema_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`timeslot_id`),
  INDEX `movieT_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `cinemaT_id_idx` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `cinemaT_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `moviereservation`.`cinemas` (`cinema_id`),
  CONSTRAINT `movieT_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviereservation`.`movies` (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviereservation`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservation`.`reservations` ;

CREATE TABLE IF NOT EXISTS `moviereservation`.`reservations` (
  `reservation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cinema_id` INT(11) NULL DEFAULT NULL,
  `time` VARCHAR(20) NULL DEFAULT NULL,
  `customer_name` VARCHAR(20) NULL DEFAULT NULL,
  `total_payment` INT(11) NULL DEFAULT NULL,
  `no_of_kid` INT(11) NULL DEFAULT NULL,
  `no_of_adult` INT(11) NULL DEFAULT NULL,
  `no_of_senior` INT(11) NULL DEFAULT NULL,
  `timeslot_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `cinemaR_id_idx` (`cinema_id` ASC) VISIBLE,
  INDEX `timeslotR_id_idx` (`timeslot_id` ASC) VISIBLE,
  INDEX `customerR_id_idx` (`customer_name` ASC) VISIBLE,
  CONSTRAINT `cinemaR_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `moviereservation`.`cinemas` (`cinema_id`),
  CONSTRAINT `timeslotR_id`
    FOREIGN KEY (`timeslot_id`)
    REFERENCES `moviereservation`.`timeslots` (`timeslot_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1002
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `moviereservation`.`seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservation`.`seats` ;

CREATE TABLE IF NOT EXISTS `moviereservation`.`seats` (
  `seat_id` INT(11) NOT NULL,
  `seat_number` INT(11) NULL DEFAULT NULL,
  `cinema_id` INT(11) NULL DEFAULT NULL,
  `reservation_id` INT(11) NULL DEFAULT NULL,
  `timeslot_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `cinemaS_id_idx` (`cinema_id` ASC) VISIBLE,
  INDEX `timeslotS_id_idx` (`timeslot_id` ASC) VISIBLE,
  INDEX `reservationS_id_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `cinemaS_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `moviereservation`.`cinemas` (`cinema_id`),
  CONSTRAINT `reservatioS_id`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `moviereservation`.`reservations` (`reservation_id`),
  CONSTRAINT `timeslotS_id`
    FOREIGN KEY (`timeslot_id`)
    REFERENCES `moviereservation`.`timeslots` (`timeslot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
