-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 16:41:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moviereservations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviereservations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviereservations` DEFAULT CHARACTER SET utf8 ;
USE `moviereservations` ;

-- -----------------------------------------------------
-- Table `moviereservations`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservations`.`movies` ;

CREATE TABLE IF NOT EXISTS `moviereservations`.`movies` (
  `movie_id` INT(11) NOT NULL,
  `movie_name` VARCHAR(40) NULL DEFAULT NULL,
  `movie_genre` VARCHAR(20) NULL DEFAULT NULL,
  `movie_director` VARCHAR(20) NULL DEFAULT NULL,
  `movie_rating` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviereservations`.`timeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservations`.`timeslots` ;

CREATE TABLE IF NOT EXISTS `moviereservations`.`timeslots` (
  `timeslot_id` INT(11) NOT NULL,
  `time_start` VARCHAR(20) NULL DEFAULT NULL,
  `time_end` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`timeslot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviereservations`.`cinemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservations`.`cinemas` ;

CREATE TABLE IF NOT EXISTS `moviereservations`.`cinemas` (
  `cinema_id` INT(11) NOT NULL,
  `movie_id` INT(11) NULL DEFAULT NULL,
  `timeslot_id` INT(11) NOT NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cinema_id`),
  INDEX `movieC_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `timeslotC_id_idx` (`timeslot_id` ASC) VISIBLE,
  CONSTRAINT `movieC_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviereservations`.`movies` (`movie_id`),
  CONSTRAINT `timeslotC_id`
    FOREIGN KEY (`timeslot_id`)
    REFERENCES `moviereservations`.`timeslots` (`timeslot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviereservations`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservations`.`customers` ;

CREATE TABLE IF NOT EXISTS `moviereservations`.`customers` (
  `customer_id` INT(11) NOT NULL,
  `customer_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviereservations`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservations`.`reservations` ;

CREATE TABLE IF NOT EXISTS `moviereservations`.`reservations` (
  `reservation_id` INT(11) NOT NULL,
  `cinema_id` INT(11) NULL DEFAULT NULL,
  `total_amount` INT(11) NULL DEFAULT NULL,
  `customer_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `cinemaR_id_idx` (`cinema_id` ASC) VISIBLE,
  INDEX `customerR_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `cinemaR_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `moviereservations`.`cinemas` (`cinema_id`),
  CONSTRAINT `customerR_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `moviereservations`.`customers` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviereservations`.`seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moviereservations`.`seats` ;

CREATE TABLE IF NOT EXISTS `moviereservations`.`seats` (
  `seat_id` INT(11) NOT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `cinema_id` INT(11) NULL DEFAULT NULL,
  `reservation_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `cinemaS_id_idx` (`cinema_id` ASC) VISIBLE,
  INDEX `reservationS_id_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `cinemaS_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `moviereservations`.`cinemas` (`cinema_id`),
  CONSTRAINT `reservationS_id`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `moviereservations`.`reservations` (`reservation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
